services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: HardPass@123
      MARIADB_DATABASE: VOTE_MANAGER
      MARIADB_USER: vote_manager
      MARIADB_PASSWORD: VoteManager@123
    ports:
      - 3307:3306
    depends_on:
      - kafka
      
  vote-challenge:
    build:
      context: ./vote-challenge
    depends_on:
      - mariadb
    environment:
      DB_URL: mariadb
      DB_PORT: 3306
      DB_USERNAME: vote_manager
      DB_PASSWORD: VoteManager@123
      KAFKA_URL: kafka
    ports:
      - "8080:8080"
    volumes:
      - /tmp/logs/vote-challenge:/logs

  agenda-processor:
    build:
      context: ./agenda-processor
    depends_on:
      - vote-challenge
    environment:
      DB_URL: mariadb
      DB_PORT: 3306
      DB_USERNAME: vote_manager
      DB_PASSWORD: VoteManager@123
      KAFKA_URL: kafka
    ports:
      - "8081:8081"
    volumes:
      - /tmp/logs/agenda-processor:/logs

  vote-visualizer:
    build:
      context: ./vote-visualizer
    depends_on:
      - agenda-processor
    environment:
      KAFKA_URL: kafka
    ports:
      - "8082:8082"
    volumes:
      - /tmp/logs/vote-visualizer:/logs
